name = "sveltia-cms-auth"
main = "src/index.js"
compatibility_date = "2023-03-24"

[vars]
ALLOWED_DOMAINS = "www.beanbarrel.coffee,beans-and-barrels.vercel.app"
GITHUB_CLIENT_ID = "Ov23liXvaK0DUTDdRsge"
